apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-service
  namespace: board
spec:
  replicas: 2
  selector:
    matchLabels:
      app: file-service
  template:
    metadata:
      labels:
        app: file-service
    spec:
      imagePullSecrets:
        - name: ghcr-regcred
      containers:
        - name: file-service
          image: ghcr.io/drsol-ha/board-file-service:v1
          ports:
            - containerPort: 5003
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: board-secrets
                  key: DATABASE_URL
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: board-secrets
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: board-secrets
                  key: DB_PASSWORD
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: board-secrets
                  key: DB_HOST
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: board-secrets
                  key: DB_NAME
          envFrom:
            - secretRef:
                name: minio-credentials
