apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend 
  namespace: board
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets:
        - name: ghcr-regcred
      containers:
        - name: frontend
          image: ghcr.io/drsol-ha/board-frontend:v1
          ports:
            - containerPort: 5000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: board-secrets
                  key: DATABASE_URL
