apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: board
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      imagePullSecrets:
        - name: ghcr-regcred
      containers:
        - name: user-service
          image: ghcr.io/drsol-ha/board-user-service:v1
          ports:
            - containerPort: 5001
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: board-secrets
                  key: DATABASE_URL
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: board-secrets
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: board-secrets
                  key: DB_PASSWORD
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: board-secrets
                  key: DB_HOST
            - name: DB_NAME
              valueFrom: 
                secretKeyRef:
                  name: board-secrets
                  key: DB_NAME

