persistence:
  enabled: true
  storageClass: local-path
  size: 20Gi
  accessMode: ReadWriteOnce

controller:
  nodeSelector:
    kubernetes.io/hostname: kube-node1
  resources:
    requests:
      cpu: "500m"
      memory: "512Mi"
    limits:
      cpu: "2"
      memory: "2Gi"
  javaOpts: "-Xms256m -Xmx768m -XX:+UseStringDeduplication"
  startupProbe:
    enabled: true
    periodSeconds: 10
    failureThreshold: 60

  ingress:
    enabled: true
    apiVersion: networking.k8s.io/v1
    ingressClassName: nginx
    hostName: jenkins.192.168.56.240.nip.io
    path: /
    pathType: Prefix
