deploymentMode: SimpleScalable

gateway:
  nginxConfig:
    resolver: "10.233.0.3"

loki:
  storage:
    type: s3
    bucketNames:
      chunks: loki-chunks
      ruler: loki-ruler
      admin: loki-admin
    s3:
      endpoint: "https://minio.minio-tenant.svc:443"
      insecure: false
      accessKeyId: minio
      secretAccessKey: minio123
      s3ForcePathStyle: true
      region: "us-east-1"

  # OTLP/structured metadata 사용 시 v13 필요
  schemaConfig:
    configs:
      - from: "2025-09-24"
        store: tsdb
        object_store: s3
        schema: v13
        index:
          prefix: loki_index_
          period: 24h

  #보조/쿼리 제한          
  limits_config:
    retention_period: 168h       # 7일 (원하는 기간으로 조절)
    max_query_length: 30d        # 필요시 확대

read:
  extraVolumes:
    - name: minio-ca
      secret: { secretName: minio-ca }
  extraVolumeMounts:
    - name: minio-ca
      mountPath: /etc/ssl/minio
      readOnly: true
  env:
    - name: SSL_CERT_FILE
      value: /etc/ssl/minio/ca.crt

write:
  podAntiAffinity: soft
  persistence:
    enabled: true
    storageClass: local-path
    storageClassName: local-path  
    size: 20Gi  
  extraVolumes:
    - name: minio-ca
      secret: { secretName: minio-ca }
  extraVolumeMounts:
    - name: minio-ca
      mountPath: /etc/ssl/minio
      readOnly: true
  env:
    - name: SSL_CERT_FILE
      value: /etc/ssl/minio/ca.crt

backend:
  podAntiAffinity: soft
  persistence:
    enabled: true
    storageClass: local-path
    storageClassName: local-path  
    size: 20Gi  
  extraVolumes:
    - name: minio-ca
      secret: { secretName: minio-ca }
  extraVolumeMounts:
    - name: minio-ca
      mountPath: /etc/ssl/minio
      readOnly: true
  env:
    - name: SSL_CERT_FILE
      value: /etc/ssl/minio/ca.crt

chunksCache:
  enabled: false
