deploymentMode: SimpleScalable

gateway:
  nginxConfig:
    resolver: "10.233.0.3"

loki:
  storage:
    type: s3
    bucketNames:
      chunks: "loki-chunks"
      ruler: "loki-ruler"
      admin: "loki-admin"
    s3:
      endpoint: "https://minio.minio-tenant.svc:443"  # ← 콘솔 말고 S3 API 서비스
      accessKeyId: "minio"
      secretAccessKey: "minio123"
      s3ForcePathStyle: true
      insecure: false  # HTTPS 사용

  schemaConfig:
    configs:
      - from: "2020-10-24"
        store: tsdb
        object_store: s3
        schema: v12
        index:
          prefix: loki_index_
          period: 24h

# SimpleScalable에서는 write/backend에 영속화를 설정
write:
  persistence:
    enabled: true
    storageClass: "local-path"
    size: 20Gi

backend:
  persistence:
    enabled: true
    storageClass: "local-path"
    size: 20Gi

chunksCache:
  enabled: false
