grafana:
  enabled: true
  adminUser: admin
  adminPassword: "admin"
  service: 
    type: ClusterIP
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts: grafana.drsol.cloud
    path: /
    pathType: Prefix

prometheus:
  prometheusSpec:
    retention: 7d
    retentionSize: "8GiB"
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false
    scrapeConfigSelectorNilUsesHelmValues: false
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: local-path
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 20Gi

alertmanager:
  enabled: true
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: local-path
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 5Gi
